title = "Ray's blog"
baseURL = 'https://raychang987.github.io/jrchang.github.io/'
languageCode = 'en-us'
theme = 'PaperMod'
enableEmoj =  true
canonifyURLs = true
RelativeURLs = true
googleAnalytics = ""
enableRobotsTXT = true
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"

[params]
author = "David Hwang"
ShowReadingTime = true
ShowShareButtons = true

  [params.homeInfoParams]
  Title = "the dev playbook"
  Content = """
Welcome to the **dev playbook** 🎉
- This is a space where I will mostly be sharing about Go & Kubernetes 🙂
"""

  [[params.socialIcons]]
  name = "Github"
  url = "https://github.com/dhij"

  [[params.socialIcons]]
  name = "Youtube"
  url = "https://www.youtube.com/@dhij"

  [[params.socialIcons]]
  name = "Rss"
  url = "index.xml"

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 30
