baseURL = 'https://raychang987.github.io/jrchang.github.io/'
languageCode = 'en-us'
title = "Ray's blog"
theme = 'PaperMod'
enableEmoj =  true


  
[[languages.en.menu.main]]
name = "Posts"
url = "posts"
weight = 5



