baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Ray's blog"
theme = 'PaperMod'
canonifyURLs = true

  
[[languages.en.menu.main]]
name = "Posts"
url = "posts"
weight = 5


[module]
  [[module.imports]]
    disable = false

